# Nombre del workflow (aparecer치 en la GUI)
name: hello-world
# Cu치ndo se ejecuta: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: push
jobs:
  # ID del job. Cada job se ejecuta en una m치quina nueva
  my-job:
    # Tipo de m치quina. Puede ser de Github o mantenida por nosotros:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"